package pojo;
// Generated Oct 21, 2020 2:52:16 AM by Hibernate Tools 4.3.1


import dao.DAOAnimal;
import java.util.Date;
import java.util.List;
import javax.faces.bean.ManagedBean;


/**
 * Animal generated by hbm2java
 */
@ManagedBean
public class Animal  implements java.io.Serializable {


     private Integer idAnimal;
     private String nama;
     private String tglLahir;
     private String keeper;
     private String negara;
     private String spesies;
     private String pemakan;

    public Animal() {
    }

    public Animal(Integer idAnimal, String nama, String tglLahir, String keeper, String negara, String spesies, String pemakan) {
       this.nama = nama;
       this.tglLahir = tglLahir;
       this.keeper = keeper;
       this.negara = negara;
       this.spesies = spesies;
       this.pemakan = pemakan;
    }
   
    public Integer getIdAnimal() {
        return this.idAnimal;
    }
    
    public void setIdAnimal(Integer idAnimal) {
        this.idAnimal = idAnimal;
    }
    public String getNama() {
        return this.nama;
    }
    
    public void setNama(String nama) {
        this.nama = nama;
    }
    public String getTglLahir() {
        return this.tglLahir;
    }
    
    public void setTglLahir(String tglLahir) {
        this.tglLahir = tglLahir;
    }
    public String getKeeper() {
        return this.keeper;
    }
    
    public void setKeeper(String keeper) {
        this.keeper = keeper;
    }
    public String getNegara() {
        return this.negara;
    }
    
    public void setNegara(String negara) {
        this.negara = negara;
    }
  
 
    public String getSpesies() {
        return this.spesies;
    }
    
    public void setSpesies(String spesies) {
        this.spesies = spesies;
    }
    public String getPemakan() {
        return this.pemakan;
    }
    
    public void setPemakan(String pemakan) {
        this.pemakan = pemakan;
    }

     public void save() 
    {
        DAOAnimal cdao = new DAOAnimal();
        cdao.add(this);
        nama="";
        tglLahir="";
        keeper="";
        negara="";
        spesies= "";
        pemakan="";
    }
     
      public List<Animal> getallrecords(){
        DAOAnimal anim = new DAOAnimal();
        List<Animal> con = anim.lihatdata();
        return con;
    }
      
    public String getbyid(){
        DAOAnimal cont = new DAOAnimal();
        List<Animal> lat = cont.cari(idAnimal);
        if(lat != null){
            nama = lat.get(0).nama;
            tglLahir = lat.get(0).tglLahir;
            keeper = lat.get(0).keeper;
            negara = lat.get(0).negara;
            spesies = lat.get(0).spesies;
            pemakan = lat.get(0).pemakan;
        return "Animal2";
    }
    return "Animal2";
}
    public void update(){
        DAOAnimal a = new DAOAnimal();
        a.ubah(this);
        nama="";
        tglLahir="";
        keeper="";
        negara="";
        spesies= "";
        pemakan="";
    }
    
    public void delete(){
        DAOAnimal a = new DAOAnimal();
        a.delete(idAnimal);
        nama="";
        tglLahir="";
        keeper="";
        negara="";
        spesies= "";
        pemakan="";
    }


}


