package pojo;
// Generated Oct 21, 2020 2:52:16 AM by Hibernate Tools 4.3.1

import dao.DAOTicket;
import java.util.Date;
import java.util.List;
import javax.faces.bean.ManagedBean;





/**
 * Ticket generated by hbm2java
 */
@ManagedBean
public class Ticket  implements java.io.Serializable {


     private int idBooking;
     private String nama;
     private String tglPesan;
     private int jumlahOrang;
     private String phone;
     private String email;

    public Ticket() {
      
    }

    public Ticket(String nama, String tglPesan, int jumlahOrang, String phone, String email) {
       this.nama = nama;
       this.tglPesan = tglPesan;
       this.jumlahOrang = jumlahOrang;
       this.phone = phone;
       this.email = email;
    }
   
    public Integer getIdBooking() {
        return this.idBooking;
    }
    
    public void setIdBooking(Integer idBooking) {
        this.idBooking = idBooking;
    }
    public String getNama() {
        return this.nama;
    }
    
    public void setNama(String nama) {
        this.nama = nama;
    }
    public String getTglPesan() {
        return this.tglPesan;
    }
    
    public void setTglPesan(String tglPesan) {
        this.tglPesan = tglPesan;
    }
    public int getJumlahOrang() {
        return this.jumlahOrang;
    }
    
    public void setJumlahOrang(int jumlahOrang) {
        this.jumlahOrang = jumlahOrang;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    
     public void save()
    {
        DAOTicket pdao = new DAOTicket();
        pdao.add(this);
        nama="";
        tglPesan="";
        jumlahOrang=0;
        phone="";
        email="";
    }

     public List<Ticket> getallrecords(){
        DAOTicket tc = new DAOTicket();
        List<Ticket> rs = tc.lihatdata();
        return rs;
    }
      
    public String getbyid(){
        DAOTicket tc = new DAOTicket();
        List<Ticket> lat = tc.cari(idBooking);
        if(lat != null){
            nama = lat.get(0).nama;
            tglPesan = lat.get(0).tglPesan;
            jumlahOrang = lat.get(0).jumlahOrang;
            phone = lat.get(0).phone;
            email = lat.get(0).email;
        return "Ticket2";
    }
    return "Ticket2";
}
    public void update(){
        DAOTicket a = new DAOTicket();
        a.ubah(this);
        nama="";
        tglPesan="";
        jumlahOrang=0;
        phone="";
        email="";
    }
    
    public void delete(){
        DAOTicket a = new DAOTicket();
        a.delete(idBooking);
        nama="";
        tglPesan="";
        jumlahOrang=0;
        phone="";
        email="";
    }
}


